Added a cmd to drop course users.
edulinq/autograder-server pull request #117
Opened 2024-11-04 23:59 UTC by OliverLok

2024-11-06 19:18 UTC, Lucas-Ellenberger requested changes
Looking great!

Nit on the description.

2024-11-06 19:18 UTC, Lucas-Ellenberger commented on cmd/course-user-drop/main.go
> +		kong.Description("Drop a user from a course."),
/s/from a course/from the course

(Match the [python interface](https://github.com/edulinq/autograder-py/blob/9642fa80dd07925f94bed620fe12497524711f32/autograder/api/courses/users/drop.py#L15)).

2024-11-06 19:50 UTC, Lucas-Ellenberger approved these changes
lgtm!

2024-11-08 02:27 UTC, eriq-augustine approved these changes
lgtm

2024-11-08 02:29 UTC, merged