Added a cmd to get a course user's information.
edulinq/autograder-server pull request #118
Opened 2024-11-05 00:12 UTC by OliverLok

2024-11-06 19:49 UTC, Lucas-Ellenberger requested changes
Looking good!

Just asking for one more test case.

2024-11-06 19:49 UTC, Lucas-Ellenberger commented on cmd/course-user-get/main_test.go
> +		},
Add one more test case for a user that exists in the database, but is not enrolled in the course.

See the python interface test case for reference (https://github.com/edulinq/autograder-py/blob/main/tests/api/testdata/courses/users/courses_users_get_not_enrolled.json).

2024-11-06 20:02 UTC, Lucas-Ellenberger approved these changes
lgtm!

2024-11-08 02:32 UTC, eriq-augustine approved these changes
lgtm

2024-11-08 02:33 UTC, merged