Added the list of endpoints to the --help section of the general API CMD.
edulinq/autograder-server pull request #130
Opened 2024-12-06 01:19 UTC by OliverLok

This makes it easier to see a list of endpoints rather than having to go to an external file.

2024-12-06 02:03 UTC, eriq-augustine requested changes
I am a bit hesitant about this one:
1) I am not convinced the the output will be clean enough to not just be a distraction. Copy example output (text, not image) into the PR conversation so we can see what it looks like when all finished.
2) What about endpoints we don't yet support? It feels a little disingenuous to list it and then smack down the user when they try and use it.

2024-12-24 07:11 UTC, eriq-augustine requested changes
As I mentioned in my last round, past the output of a run in the comments so I can see what it looks like.

2024-12-24 07:11 UTC, eriq-augustine commented on cmd/call-endpoint/main.go
> +	Endpoint   string   `help:"Endpoint of the desired API." arg:"" optional:""`
Now that this is optional, there should be some sort of special case for handling when it is not specified.
Think about how you want to user to experience it.

2024-12-24 07:11 UTC, eriq-augustine commented on cmd/call-endpoint/main.go
> +	for endpoint := range apiDescription.Endpoints {
I don't like one-valued map range (I don't think it is as clear as using an empty value).
Put in an underscore for the value.

2025-02-11 23:42 UTC, OliverLok commented
> As I mentioned in my last round, past the output of a run in the comments so I can see what it looks like.

Output from using --list:
courses/users/get
courses/assignments/submissions/remove
courses/assignments/submissions/analysis/pairwise
courses/users/enroll
courses/assignments/submissions/fetch/user/attempt
courses/users/drop
system/stacks
users/password/change
courses/stats/query
courses/upsert/filespec
metadata/describe
courses/upsert/zip
lms/user/get
courses/admin/update
courses/assignments/list
courses/lms/scores/upload
users/auth
users/password/reset
courses/assignments/submissions/fetch/user/attempts
courses/assignments/submissions/fetch/user/history
courses/assignments/submissions/fetch/user/peek
users/get
users/list
users/upsert
courses/assignments/get
courses/assignments/submissions/submit
stats/system/query
users/tokens/create
courses/assignments/submissions/analysis/individual
lms/upload/scores
users/remove
logs/query
users/tokens/delete
courses/assignments/submissions/fetch/course/attempts
courses/assignments/submissions/fetch/course/scores
courses/users/list

2025-02-11 23:52 UTC, eriq-augustine requested changes
Now that I see the output, this generally makes sense to me.

2025-02-11 23:52 UTC, eriq-augustine commented on cmd/call-endpoint/main.go
> +		kong.Description("Execute an API request to a specified endpoint."),
I'm not a fan of this description.
"Executing" "to" something sounds strange.
"Sending" a request "to" and endpoint makes sense.
Or maybe use "call" to be symmetric with the CMD's name.

2025-02-11 23:52 UTC, eriq-augustine commented on cmd/call-endpoint/main.go
> +		// Return to prevent further execution after listing endpoints.
I don't think the comment (or space) are necessary here.
What you are doing is pretty clear.

2025-02-11 23:52 UTC, eriq-augustine commented on cmd/call-endpoint/main.go
> +func listAPIEndpoints() {
This should sort the endpoints.

2025-02-11 23:52 UTC, eriq-augustine commented on cmd/call-endpoint/main_test.go
> +				ExpectedStderrSubstring: `Failed to find the endpoint. See --list to view all endpoints. | {"endpoint":"ZZZ"}`,
s/See/Use/

"See" really only makes sense if your are looking up or referencing something.
Here you are invoking the executable again with a new flag.

2025-02-12 00:11 UTC, OliverLok commented
> As I mentioned in my last round, past the output of a run in the comments so I can see what it looks like.

Sorted list of endpoints:
courses/admin/update
courses/assignments/get
courses/assignments/list
courses/assignments/submissions/analysis/individual
courses/assignments/submissions/analysis/pairwise
courses/assignments/submissions/fetch/course/attempts
courses/assignments/submissions/fetch/course/scores
courses/assignments/submissions/fetch/user/attempt
courses/assignments/submissions/fetch/user/attempts
courses/assignments/submissions/fetch/user/history
courses/assignments/submissions/fetch/user/peek
courses/assignments/submissions/remove
courses/assignments/submissions/submit
courses/lms/scores/upload
courses/stats/query
courses/upsert/filespec
courses/upsert/zip
courses/users/drop
courses/users/enroll
courses/users/get
courses/users/list
lms/upload/scores
lms/user/get
logs/query
metadata/describe
stats/system/query
system/stacks
users/auth
users/get
users/list
users/password/change
users/password/reset
users/remove
users/tokens/create
users/tokens/delete
users/upsert

2025-02-12 00:23 UTC, eriq-augustine requested changes
Nice, just a few things.

2025-02-12 00:23 UTC, eriq-augustine commented on cmd/call-endpoint/main.go
> +		kong.Description("Call an endpoint to perform an API request."),
This sill sounds a bit overly complicated.
Specifically, the last half sounds redundant (if you are calling an API endpoint you must be making a request).

2025-02-12 00:23 UTC, eriq-augustine commented on cmd/call-endpoint/main.go
> +		// Return to prevent further execution after log.Error().
Last round there was a comment that removed this same substring (these two lines) from the case above.
Remember that style comments generally apply to the entire PR.

2025-02-12 00:23 UTC, eriq-augustine commented on cmd/call-endpoint/main.go
> +	sort.Strings(endpoints)
I would use slices.Sort() instead.
It's not a big deal, but modern Go (since generics) just calls the slices version.
https://pkg.go.dev/sort#Strings

2025-02-12 00:53 UTC, eriq-augustine approved these changes
lgtm!

2025-02-12 00:53 UTC, merged